select
    O.*
--FROM RAW_CUSTOMER
    , C.*
--FROM RAW_PRODUCT
    , P.*
    , (O.ORDER_SELLING_PRICE - O.ORDER_COST_PRICE) AS ORDER_PROFIT
FROM
    {{ ref('RAW_ORDERS') }} AS O
LEFT JOIN
    {{ ref('RAW_CUSTOMER') }} AS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
LEFT JOIN
    {{ ref('RAW_PRODUCTS') }} AS P
ON P.PRODUCT_ID = O.PRODUCT_ID